spring.application.name=Proyecto_LaboSoftw

#Puerto donde se ejecuta la app (http://localhost:8081)
server.port=8081

# Logs de error para ver problemas de deserialización
logging.level.org.springframework.http.converter.json=DEBUG

# Configuración básica para usar H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:LABORABD
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostrar consultas en consola
spring.jpa.show-sql=true

# Crear tablas automáticamente
spring.jpa.hibernate.ddl-auto=none

# Consola web de H2
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console 
#para ingresar a la consola web de H2, ir a http://localhost:8081/h2-console
